services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fifa_wc_bracket
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_SECRET_KEY: "change-this-in-portainer"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"
      DJANGO_STATIC_URL: "http://10.45.67.52:8241/"
      BRACKET_ADMIN_CODE: "change-me"
      DJANGO_DB_HOST: "10.45.67.52"
      DJANGO_DB_PORT: "5432"
      DJANGO_DB_NAME: "fifa"
      DJANGO_DB_USER: "fifa_user"
      DJANGO_DB_PASSWORD: "change-me"
      DJANGO_DB_CONN_MAX_AGE: "60"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "change-me"
