# Generated by Django 6.0.6 on 2026-06-28 14:48

import django.db.models.deletion
from django.db import migrations, models


ROUND_SIZES = [16, 8, 4, 2, 1]
DEFAULT_TEAMS = [
    "South Africa", "Canada", "Netherlands", "Morocco",
    "Germany", "Paraguay", "France", "Sweden",
    "Belgium", "Senegal", "United States", "Bosnia and Herzegovina",
    "Spain", "Austria", "Portugal", "Croatia",
    "Brazil", "Japan", "Ivory Coast", "Norway",
    "Mexico", "Ecuador", "England", "DR Congo",
    "Switzerland", "Algeria", "Colombia", "Ghana",
    "Argentina", "Cabo Verde", "Australia", "Eqypt",
]


def seed_teams_and_matches(apps, schema_editor):
    Team = apps.get_model('bracket', 'Team')
    Match = apps.get_model('bracket', 'Match')

    team_map = {}
    for name in DEFAULT_TEAMS:
        team, _ = Team.objects.get_or_create(name=name)
        team_map[name] = team

    if Match.objects.exists():
        return

    # Round of 32 pairs from the configured team order.
    for match_index in range(ROUND_SIZES[0]):
        home_name = DEFAULT_TEAMS[match_index * 2]
        away_name = DEFAULT_TEAMS[match_index * 2 + 1]
        Match.objects.create(
            round_index=0,
            match_index=match_index,
            home_team=team_map[home_name],
            away_team=team_map[away_name],
            winner=None,
        )

    # Later rounds start with empty participants and are auto-populated from prior round winners.
    for round_index in range(1, len(ROUND_SIZES)):
        for match_index in range(ROUND_SIZES[round_index]):
            Match.objects.create(round_index=round_index, match_index=match_index)


def unseed_teams_and_matches(apps, schema_editor):
    Team = apps.get_model('bracket', 'Team')
    Match = apps.get_model('bracket', 'Match')
    Match.objects.all().delete()
    Team.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_index', models.PositiveSmallIntegerField()),
                ('match_index', models.PositiveSmallIntegerField()),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='bracket.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='bracket.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='bracket.team')),
            ],
            options={
                'ordering': ['round_index', 'match_index'],
                'constraints': [models.UniqueConstraint(fields=('round_index', 'match_index'), name='unique_round_match')],
            },
        ),
        migrations.RunPython(seed_teams_and_matches, unseed_teams_and_matches),
    ]
