# Generated by Django 6.0.6 on 2026-06-28 15:37

import bracket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0002_team_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketentry',
            name='eligible_mask',
            field=models.JSONField(default=bracket.models.default_eligible_mask),
        ),
    ]
