# Generated by Django 6.0.6 on 2026-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0003_bracketentry_eligible_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='kickoff_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
