# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0004_match_kickoff_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_pk',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_pk',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
