# Generated by Django 6.0.6 on 2026-07-01 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0005_match_scores_and_pks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=True)),
                ('points_awarded', models.SmallIntegerField(default=0)),
                ('picked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_picks', to='bracket.bracketentry')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_picks', to='bracket.match')),
                ('picked_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_in_entries', to='bracket.team')),
            ],
            options={
                'ordering': ['entry_id', 'match__round_index', 'match__match_index'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'match'), name='unique_entry_match_pick')],
            },
        ),
    ]
